### ISSUE TITLE
Fase 3 Firebase

### ISSUE THREAD

**Issue by Rodrigo-Roger** [Rodrigo-Roger/Fase3#1]
Primeiro devemos criar uma pasta aqui estamos chamando de "context", e um arquivo .js que está sendo chamado de "UsuarioContext.js", nesse arquivo deve conter as funções context e provinder que serve para gerenciarmos as autenticações dos valores fonecidos pelos usuarios, e seus ID's. 
![pb1](https://user-images.githubusercontent.com/83319104/177217623-85852008-9cb6-42f7-8532-120825699685.png)

**Comment by annabalves** [comment]
Quando fizermos a importação do "createContext" e do "useState", vamos fazer a criação e chamar as constantes de UsuarioContext e UsuarioProvider para dar o retorno dos valores e fazer a destribuição e ação devida.
![pb2](https://user-images.githubusercontent.com/101371543/177218437-fb104542-505d-4a69-a742-993acae9c49a.png)
 O UsuarioProvider tem como função receber os estados Props e distribuir para as "children" especificas já o UsuarioContext tem a função de passar as props de forma implicita para os componetes desejados deixando disponivél o context para todos.

**Comment by Rodrigo-Roger** [comment]
Nas areas que desejamos pedir o login do usuario, devemos criar funções com o objetivo de registrar esses dados para o registro...
![pb3](https://user-images.githubusercontent.com/83319104/177218991-5f9d0ec0-9453-4193-83e3-450973953377.png)

**Comment by annabalves** [comment]
Após esse armazenamento no banco é possivél fazermos o login, com o usuario e senha criados, aqui tambem devemos reutilizar as funções
![image](https://user-images.githubusercontent.com/101371543/177219091-5da3c8cc-4486-4a9e-9282-f874b2962c5b.png)

**Comment by Rodrigo-Roger** [comment]
![image](https://user-images.githubusercontent.com/83319104/177219920-ff1cc316-f8e9-41b1-a244-92998d9f1a14.png)

é possivél vermos tambem o botão que sera responsavel por validar os valores

**Comment by Rodrigo-Roger** [comment]
aqui está nossa pasta "app.js", responsalvel por manusear os eventos
![image](https://user-images.githubusercontent.com/83319104/177220383-72a4d230-159f-41e1-8a3c-f447d28fcae1.png)
